export const skillCategories = [
  {
    title: "Frontend Development",
    color: "primary",
    skills: [
      "React.js",
      "Next.js",
      "Remix",
      "TypeScript",
      "JavaScript (ES6+)",
      "Redux Toolkit",
      "Zustand",
      "React Query",
      "Tailwind CSS",
      "Styled Components",
      "Framer Motion",
      "React Hook Form",
      "React Testing Library",
      "Storybook",
      "HTML5 & CSS3",
      "Responsive & Accessible Design",
      "Component Architecture",
      "Performance Optimization",
    ],
  },
  {
    title: "Backend Development",
    color: "primary",
    skills: [
      "Node.js",
      "Express.js",
      "NestJS",
      "Fastify",
      "MongoDB",
      "PostgreSQL",
      "RESTful API Design",
      "GraphQL",
      "Authentication & Authorization (JWT, OAuth2)",
      "WebSockets",
      "Microservices Architecture",
      "Server-Side Rendering (SSR)",
      "Testing (Jest, Supertest, Mocha)",
    ],
  },
  {
    title: "Blockchain & Smart Contracts",
    color: "accent",
    skills: [
      "Solidity",
      "Ethereum",
      "Hardhat",
      "OpenZeppelin",
      "ERC20 / ERC721 / ERC1155 Standards",
      "Smart Contract Security",
      "Gas Optimization",
      "Testing & Deployment Automation",
    ],
  },
  {
    title: "Web3 Integration",
    color: "primary",
    skills: [
      "ethers.js",
      "wagmi",
      "viem",
      "RainbowKit",
      "WalletConnect",
      "Web3Modal",
      "Alchemy",
    ],
  },
  {
    title: "Tools & Technologies",
    color: "accent",
    skills: [
      "Git & GitHub",
      "GitHub Actions (CI/CD)",
      "Docker & Containerization",
      "Vercel / Netlify / AWS",
      "Nginx & Deployment",
      "Linux & CLI",
      "ESLint / Prettier",
      "Figma & Design Systems",
      "Agile & Scrum Practices",
      "Unit & Integration Testing",
    ],
  },
]
export const certificates = [
  {
    title: "RS6515 - Blockchain development",
    description: `Developing a Decentralized Application with
Blockchain Technologies (Alyra School)`,
  },
]
